In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [12]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [13]:
type(arr)

numpy.ndarray

In [14]:
arr.shape

(3,)

In [8]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
type(arr)

numpy.ndarray

In [10]:
arr.shape

(2, 3)

In [19]:
arr = np.array([[[1, 2, 3, 4],
                 [3, 4, 3, 4],
                 [5, 6, 3, 4]],
                [[7, 8, 3, 4],
                 [9, 10, 3, 4],
                 [11, 12, 3, 4]]])
print(arr)

[[[ 1  2  3  4]
  [ 3  4  3  4]
  [ 5  6  3  4]]

 [[ 7  8  3  4]
  [ 9 10  3  4]
  [11 12  3  4]]]


In [20]:
type(arr)

numpy.ndarray

In [21]:
arr.shape

(2, 3, 4)

arr.shape가 (2, 3, 3)

#### ndarray 데이터 타입
- https://velog.io/@fiifa92/ndarray%EC%9D%98-%EC%B0%A8%EC%9B%90%EA%B3%BC-%EB%8D%B0%EC%9D%B4%ED%84%B0-%ED%83%80%EC%9E%85
- 숫자, 문자, boolean 
    - 숫자 - int(8, 16, 32bit), unsigned int(8, 16, 32bit), float(16, 32, 64, 128bit)
    - 문자 - <U11(유니코드)
- 하나의 데이터 타입만 가짐
    - int + float => float
    - int + 문자 => <U1

In [22]:
arr = np.array([1, 2, 3])
arr.dtype

dtype('int32')

In [23]:
arr = np.array([1.0, 2.0, 3.0])
arr.dtype

dtype('float64')

In [24]:
arr = np.array(['1', '2', '3'])
arr.dtype

dtype('<U1')

In [25]:
arr = np.array([1, 2, 3.0])
arr.dtype

dtype('float64')

In [27]:
arr = np.array([1, 2.0, '3'])
arr.dtype

dtype('<U32')

- astype

In [29]:
arr = np.array([1, 2, 3])
print(arr.dtype)

arr2 = arr.astype('float64')
print(arr2)
print(arr2.dtype)

int32
[1. 2. 3.]
float64


In [30]:
arr = np.array(['1', '2', '3'])
print(arr.dtype)

arr2 = arr.astype('int32')
print(arr2)
print(arr2.dtype)

<U1
[1 2 3]
int32


#### 여러가지 생성 방법

- arange

In [32]:
for i in range(1, 10):
    print(i)

1
2
3
4
5
6
7
8
9


In [33]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
type(np.arange(1, 10))

numpy.ndarray

In [35]:
arr = np.array(np.arange(1, 10))
print(arr)

[1 2 3 4 5 6 7 8 9]


- ones

In [36]:
arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [37]:
arr = np.ones((2, 3), dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]]


In [38]:
arr = np.ones((2, 3, 4), dtype=int)
print(arr)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


- zeros

In [39]:
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [40]:
arr = np.zeros((2, 3), dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]]


In [41]:
arr = np.zeros((2, 3, 4), dtype=int)
print(arr)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


- empty

In [43]:
arr = np.empty((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [44]:
arr = np.empty((2, 3, 5))
print(arr)

[[[1.40430692e-311 1.02765654e-321 0.00000000e+000 0.00000000e+000
   8.90105596e-307]
  [5.02034658e+175 6.82033073e-067 7.16796318e-038 6.75539055e-067
   8.24050041e-067]
  [1.81378514e-052 6.15664684e-144 3.59751658e+252 3.96046095e+246
   1.04918621e-153]]

 [[7.69165785e+218 5.04621343e+180 1.04917822e-153 9.08366793e+223
   6.82033073e-067]
  [7.16796318e-038 6.75539055e-067 8.24050041e-067 1.04917706e-153
   1.94918966e-153]
  [1.48339425e-076 9.71520605e-067 1.42670730e-071 2.59027896e-144
   7.79952704e-143]]]


- full

In [45]:
arr = np.full((2, 3), 5, dtype=int)
print(arr)

[[5 5 5]
 [5 5 5]]


In [46]:
arr = np.full((5, 2), [4, 5], dtype=int)
print(arr)

[[4 5]
 [4 5]
 [4 5]
 [4 5]
 [4 5]]
