In [1]:
import numpy as np

#### reshape
- 차원과 크기를 변경
- 변경되는 전체의 수가 변경 전의 전체수가 동일해야 함 
- ndim : 차원수

In [3]:
arr = np.arange(12)
print(arr)
print(arr.shape)
print(arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
1


In [10]:
arr2 = arr.reshape(3, 4)
print(arr2)
print(arr2.shape)
print(arr2.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [13]:
arr3 = arr.reshape(2, 3, 2)
print(arr3)
print(arr3.shape)
print(arr3.ndim)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
(2, 3, 2)
3


In [14]:
arr4 = arr.reshape(2, 3, 2)
print(arr4)
print(arr4.shape)
print(arr4.ndim)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
(2, 3, 2)
3


In [16]:
arr5 = arr4.reshape(12)
print(arr5)
print(arr5.shape)
print(arr5.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
1


-1

In [20]:
arr.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
arr.reshape(-1, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [22]:
arr.reshape(-1, -1)

ValueError: can only specify one unknown dimension

In [23]:
arr.reshape(5, -1)

ValueError: cannot reshape array of size 12 into shape (5,newaxis)

#### 다차원 배열을 1차원으로
- ravel
- flatten
- reshape
- flatten은 값을 복사해서 새로운 배열을 생성하고 ravel, reshape는 값을 참조하여 생성
    - https://m.blog.naver.com/wideeyed/221533365486

In [24]:
arr1 = np.arange(12).reshape(3, 4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
arr2 = arr1.ravel()
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [26]:
arr3 = arr1.reshape(-1)
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [27]:
arr4 = arr1.flatten()
print(arr4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


- 원본값 변경

In [28]:
arr1[0][0] = 33

In [29]:
arr1

array([[33,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
arr2

array([33,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
arr3

array([33,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])