In [1]:
# numpy 사용
import numpy as np

In [68]:
import random

# 0과 1미만 사이의 랜덤값
print(random.random())

# 범위(1이상 10 미만 중에 2간격으로 random값 - 정수값 return)
rn1 = random.randrange(1,10,2)
print(rn1)

# 범위(1이상 10이하 - 정수값 return)
rn2 = random.randint(1,10)
print(rn2)

0.7058072434729014
9
3


### rand : 0과 1 사이의 랜덤값(균등분포)

In [70]:
arr = np.random.rand(2, 3, 4)
print(arr)

[[[0.31169207 0.4394369  0.79533404 0.15655809]
  [0.0950955  0.39572464 0.52601421 0.20258337]
  [0.91898254 0.79816922 0.49552476 0.25599397]]

 [[0.75168526 0.44745373 0.23012162 0.4038626 ]
  [0.80230468 0.35502    0.37358598 0.14308481]
  [0.66231784 0.67354217 0.21531362 0.66654467]]]


### randn : 정규분포, 가우시안 분포 난수값

In [72]:
arr = np.random.randn(2, 3, 4)
print(arr)

[[[-0.91204647  0.31540799 -0.7703666  -1.45699392]
  [-1.28498474 -1.01737974 -0.63571783  0.0760175 ]
  [-0.15694752 -0.97133649 -0.97782139 -0.34100739]]

 [[-0.34618633 -0.93949008  0.84358637 -0.36079657]
  [-2.5799188  -1.05126213  0.32739801  0.61139123]
  [ 1.50688103  0.02666231 -0.57566123  0.14252729]]]


#### randint: 정수 난수 값

In [104]:
# 0이상 3미만의 랜덤값.
arr = np.random.randint(3, size=6)
print(arr)

[1 0 2 2 1 0]


In [106]:
# 3이상 10미만의 랜덤값.
arr = np.random.randint(3,10, size=6)
print(arr)

[6 9 8 3 5 4]


In [109]:
# 3이상 10미만의 랜덤값.   size 2X4
arr = np.random.randint(3,10, size=(3,4))
print(arr)

[[4 3 8 4]
 [9 6 7 3]
 [5 4 6 7]]


In [110]:
np.random.seed(35)
arr = np.random.randn(2, 3)
print(arr)

[[-1.88973671 -0.41359218 -0.76602601]
 [-0.92412667 -1.42159783  0.80525599]]


In [111]:
np.random.seed(35)

In [114]:
arr = np.random.randn(2,3)
print(arr)

[[-0.67615116 -0.16622659  0.46743519]
 [ 0.33371911 -0.84965782  0.06868276]]
