In [1]:
import numpy as np

### 연산
 - add
 - subtract
 - multiply
 - divide

 - 1.add

In [3]:
arr1 = np.arange(1, 11).reshape(2,5)
print(arr1)
arr2 = np.random.randint(1, 10 ,size=10).reshape(2, 5)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[4 9 8 4 2]
 [6 2 9 6 9]]


In [4]:
print(arr1 + arr2)

[[ 5 11 11  8  7]
 [12  9 17 15 19]]


In [5]:
print(np.add(arr1, arr2))

[[ 5 11 11  8  7]
 [12  9 17 15 19]]


In [6]:
arr3 = arr2.reshape(5, 2)
print(arr3)

[[4 9]
 [8 4]
 [2 6]
 [2 9]
 [6 9]]


- 2.subtract

In [7]:
arr1 - arr2

array([[-3, -7, -5,  0,  3],
       [ 0,  5, -1,  3,  1]])

In [9]:
arr1 * arr2

array([[ 4, 18, 24, 16, 10],
       [36, 14, 72, 54, 90]])

In [10]:
np.multiply(arr1, arr2)

array([[ 4, 18, 24, 16, 10],
       [36, 14, 72, 54, 90]])

In [11]:
arr1 / arr2

array([[0.25      , 0.22222222, 0.375     , 1.        , 2.5       ],
       [1.        , 3.5       , 0.88888889, 1.5       , 1.11111111]])

In [14]:
arr1 = np.arange(3)
print(arr1)

[0 1 2]


In [16]:
print(arr1 * 5)
print(arr1 - 5)

[ 0  5 10]
[-5 -4 -3]


In [ ]:
# [3,3] + 
arr1 = np.arange(1, 10).reshape(3, 3)