In [6]:
# numpy 사용하기
import numpy as np

In [7]:
np.array([1, 2, 3])

array([1, 2, 3])

In [21]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [22]:
type(arr)

numpy.ndarray

In [23]:
arr.shape

(3,)

In [34]:
# 2차원 배열
arr = np.array( [[1, 2, 3], 
                 [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
type(arr)

numpy.ndarray

In [36]:
arr.shape

(2, 3)

In [28]:
arr3 = np.array([[1,2],
                 [4,5],
                 [7,8]])
arr3

array([[1, 2],
       [4, 5],
       [7, 8]])

In [29]:
arr3.shape

(3, 2)

In [38]:
# 3차원배열
arr3 = np.array([[[1,2],
                 [3,4],
                 [5,6]],
                [[7, 8],
                 [9,10],
                 [11,12]]])
arr3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [37]:
arr3.shape

(2, 3, 2)

In [ ]:
arr = np.array( [[[1, 2, 3, 4],
                  [3, 4, 3, 4],
                  [5, 6, 3, 4],
                 ]])

### arr.shape가 (2, 3, 3)

In [40]:
arr = np.array( [[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                
                 [[10,11,12],
                  [13,14,15],
                  [16,17,18]]] )
arr      

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [41]:
arr.shape

(2, 3, 3)

In [45]:
arr=np.array([1, 2, 3])
arr.dtype

dtype('int32')

In [47]:
arr=np.array([1.0, 2.0, 3.0])
arr.dtype

dtype('float64')

In [48]:
arr=np.array(["1", "2", "3"])
arr.dtype

dtype('<U1')

In [50]:
arr=np.array([1, 2.0, "3"])
arr.dtype

dtype('<U32')

- astype

In [60]:
arr = np.array( [1, 2, 3])
print(arr.dtype)

arr2 = arr.astype('float64')
print(arr2)
print(arr2.dtype)

int32
[1. 2. 3.]
float64


In [62]:
arr = np.array( ["1", "2", "3"])
print(arr.dtype)

arr2 = arr.astype('int32')
print(arr2)
print(arr2.dtype)

<U1
[1 2 3]
int32


#### 여러가지 생성 방법.

- arange

In [65]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [75]:
type(np.arange(1,10))

numpy.ndarray

In [77]:
arr = np.array(np.arange(1,10))
print(arr)

[1 2 3 4 5 6 7 8 9]


- ones

In [81]:
arr = np.ones((2,3,4), dtype=int)
print(arr)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


- zeros

In [90]:
arr = np.zeros((2,3), dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]]


In [91]:
arr = np.zeros((2,3,4), dtype=int)
print(arr)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


- empty

In [94]:
arr = np.empty((2,3,5))
print(arr)

[[[1.15920871e-311 1.02271589e-321 0.00000000e+000 0.00000000e+000
   8.90105596e-307]
  [5.02034658e+175 6.69903730e+170 3.92797671e-033 3.83624607e+175
   3.50294786e-033]
  [3.53828852e-033 4.25942540e-096 1.12855837e+277 8.76730979e+252
   2.59027920e-144]]

 [[3.80985069e+180 1.14428494e+243 2.59027907e-144 7.79952704e-143
   1.36367512e+161]
  [6.23388086e+174 6.15555475e+170 4.85258238e-033 2.59027857e-144
   2.59903818e-144]
  [4.96803199e-091 1.08822735e-071 1.38347958e-047 1.11475752e+261
   1.16318408e-028]]]


- full

In [95]:
arr = np.full((2,3), 4, dtype=int)
print(arr)

[[4 4 4]
 [4 4 4]]


In [98]:
array = np.full((5,7), 3)
print(array)

[[3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]]


In [100]:
arr = np.full((5,2), [4, 5], dtype=int)
print(arr)

[[4 5]
 [4 5]
 [4 5]
 [4 5]
 [4 5]]
